# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'waytoex' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'SnapKit', '~> 3.1.2'
    pod 'Alamofire', '~> 4.2.0'
    pod 'ObjectMapper', '~> 2.1.0'
    #pod 'AlamofireObjectMapper', '~> 4.0.1'
    pod 'AlamofireObjectMapper'
    pod 'Ji', '~> 2.0.1'
    pod 'DrawerController', '~> 3.1.0'
    pod 'Kingfisher', '~> 3.2.4'
    pod 'KeychainSwift', '~> 7.0.0'
    pod 'KVOController', '~> 1.2.0'
    pod 'YYText', '~> 1.0.7'
    pod 'FXBlurView', '~> 1.6.4'
    pod 'SVProgressHUD', '~> 1.1.3'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'CXSwipeGestureRecognizer', '~> 1.0.2'
    pod '1PasswordExtension', '~> 1.8.4'
    pod 'Shimmer', '~> 1.0.2'
    pod 'Fabric'
    pod 'Crashlytics'
  # Pods for waytoex

  target 'waytoexTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
